package reporter

import (
	"bytes"
	"errors"
	"io"
	"strings"
	"testing"

	"gopkg.in/yaml.v3"

	"github.com/thoreinstein/tfperms/internal/resolver"
)

// TestRenderRoleStructure pins the wire shape of the YAML body. The
// rendered document must round-trip through yaml.Unmarshal into a map
// whose `title`, `stage`, and `includedPermissions` keys carry the
// expected values. Round-tripping (rather than substring-matching the
// raw bytes) keeps the assertion robust against yaml.v3 whitespace or
// quoting tweaks while still catching regressions that drop a field or
// emit a wrong key name (e.g. `includedpermissions` all-lower).
func TestRenderRoleStructure(t *testing.T) {
	res := resolver.Result{
		TotalApplyPerms: []string{
			"storage.buckets.get",
			"bigquery.datasets.create",
			"storage.buckets.create",
		},
	}

	var buf bytes.Buffer
	if err := RenderRole(&buf, res, "my_role", "1.2.3", "2026-05-08"); err != nil {
		t.Fatalf("RenderRole: %v", err)
	}

	body := stripYAMLComments(buf.String())

	var got map[string]any
	if err := yaml.Unmarshal([]byte(body), &got); err != nil {
		t.Fatalf("rendered YAML failed to round-trip through yaml.Unmarshal: %v\n--- output ---\n%s", err, buf.String())
	}

	if got["title"] != "my_role" {
		t.Errorf("title: got %v, want %q", got["title"], "my_role")
	}
	if got["stage"] != "GA" {
		t.Errorf("stage: got %v, want %q", got["stage"], "GA")
	}

	rawPerms, ok := got["includedPermissions"]
	if !ok {
		t.Fatalf("includedPermissions missing from output; full doc: %#v", got)
	}
	permsAny, ok := rawPerms.([]any)
	if !ok {
		t.Fatalf("includedPermissions is not a list; got %T (%v)", rawPerms, rawPerms)
	}
	gotPerms := make([]string, 0, len(permsAny))
	for _, p := range permsAny {
		s, ok := p.(string)
		if !ok {
			t.Fatalf("includedPermissions entry is not a string; got %T (%v)", p, p)
		}
		gotPerms = append(gotPerms, s)
	}

	// Permissions must be sorted (alphabetical) — the contract is
	// "Canonicalize on entry, then walk in natural order". Without
	// this, the YAML emitted from a Result with an unsorted
	// TotalApplyPerms would carry whatever order the resolver
	// happened to produce, which yaml.v3 preserves verbatim.
	wantPerms := []string{
		"bigquery.datasets.create",
		"storage.buckets.create",
		"storage.buckets.get",
	}
	if len(gotPerms) != len(wantPerms) {
		t.Fatalf("includedPermissions length: got %d (%v), want %d (%v)", len(gotPerms), gotPerms, len(wantPerms), wantPerms)
	}
	for i, p := range wantPerms {
		if gotPerms[i] != p {
			t.Errorf("includedPermissions[%d]: got %q, want %q (full got: %v)", i, gotPerms[i], p, gotPerms)
		}
	}
}

// TestRenderRoleHeader pins the format of the YAML comment header.
// The header has to (a) name tfperms, (b) include the version and
// date threaded in from main.version / main.date, and (c) include a
// runnable `gcloud iam roles create` command using the supplied
// roleName as the role ID. A reviewer reading the file should be able
// to apply it without consulting the tfperms docs.
func TestRenderRoleHeader(t *testing.T) {
	var buf bytes.Buffer
	if err := RenderRole(&buf, resolver.Result{}, "my_role", "1.2.3", "2026-05-08"); err != nil {
		t.Fatalf("RenderRole: %v", err)
	}

	got := buf.String()

	wantPrefix := "# Generated by tfperms 1.2.3 on 2026-05-08\n"
	if !strings.HasPrefix(got, wantPrefix) {
		t.Errorf("output header should start with %q; got:\n%s", wantPrefix, got)
	}

	wantGcloud := "#   gcloud iam roles create my_role --project=PROJECT_ID --file=role.yaml\n"
	if !strings.Contains(got, wantGcloud) {
		t.Errorf("output header missing gcloud command line %q;\nfull output:\n%s", wantGcloud, got)
	}
}

// TestRenderRoleCanonicalizesInput pins that RenderRole canonicalises
// its input — a Result with an unsorted TotalApplyPerms is rendered
// with the permissions sorted, matching the reporter's
// "Canonicalize on entry" contract that Render also follows.
func TestRenderRoleCanonicalizesInput(t *testing.T) {
	res := resolver.Result{
		TotalApplyPerms: []string{
			"z.a.b",
			"a.b.c",
			"m.n.o",
		},
	}

	var buf bytes.Buffer
	if err := RenderRole(&buf, res, "role_x", "v", "d"); err != nil {
		t.Fatalf("RenderRole: %v", err)
	}

	body := stripYAMLComments(buf.String())
	idxA := strings.Index(body, "a.b.c")
	idxM := strings.Index(body, "m.n.o")
	idxZ := strings.Index(body, "z.a.b")
	if idxA < 0 || idxM < 0 || idxZ < 0 {
		t.Fatalf("rendered YAML missing expected permissions; body:\n%s", body)
	}
	if !(idxA < idxM && idxM < idxZ) {
		t.Errorf("permissions not alphabetically ordered in output; got order indexes a=%d m=%d z=%d\nbody:\n%s",
			idxA, idxM, idxZ, body)
	}
}

// TestRenderRoleEmptyPermissions pins the empty-result path: a Result
// with no permissions still produces a valid YAML document — the
// `includedPermissions` field is present but its list is empty. A
// downstream `gcloud` invocation against an empty role would no-op,
// but the file still has to parse cleanly.
func TestRenderRoleEmptyPermissions(t *testing.T) {
	var buf bytes.Buffer
	if err := RenderRole(&buf, resolver.Result{}, "empty_role", "v", "d"); err != nil {
		t.Fatalf("RenderRole: %v", err)
	}

	body := stripYAMLComments(buf.String())
	var got map[string]any
	if err := yaml.Unmarshal([]byte(body), &got); err != nil {
		t.Fatalf("rendered YAML failed to round-trip: %v\n--- output ---\n%s", err, buf.String())
	}
	rawPerms, ok := got["includedPermissions"]
	if !ok {
		t.Fatalf("includedPermissions key missing from empty-result output; full doc: %#v", got)
	}
	// yaml.v3 marshals a non-nil empty slice as `[]`, which round-trips
	// to a non-nil empty []any. A nil slice would marshal as `null`,
	// which round-trips to a nil rawPerms — still acceptable for an
	// empty role, but pinning the empty-list shape protects against a
	// regression that flips the marshalling.
	if rawPerms != nil {
		permsAny, ok := rawPerms.([]any)
		if !ok {
			t.Fatalf("includedPermissions is not a list; got %T", rawPerms)
		}
		if len(permsAny) != 0 {
			t.Errorf("includedPermissions for empty Result should have zero entries; got %v", permsAny)
		}
	}
}

// TestRenderRolePropagatesWriteErrors mirrors the Render write-error
// contract: a broken pipe mid-document must surface as a non-nil
// return rather than silent truncation. Without this, a CI consumer
// piping the YAML into `gcloud` would see an exit code 0 against a
// half-written file and fail downstream with a less-specific error.
func TestRenderRolePropagatesWriteErrors(t *testing.T) {
	res := resolver.Result{TotalApplyPerms: []string{"a.b.c"}}

	w := &failingWriter{byteBudget: 8}
	err := RenderRole(w, res, "role_x", "v", "d")
	if err == nil {
		t.Fatal("RenderRole with a failing writer returned nil; expected the broken-pipe error to be propagated")
	}
	if !errors.Is(err, errBrokenPipe) {
		t.Errorf("RenderRole error chain does not wrap the underlying writer error.\nerr: %v", err)
	}
}

// TestRenderRolePropagatesShortWrites pins the short-write latch for
// the role formatter — same regression class as Render's
// TestRenderPropagatesShortWrites. A writer that returns
// (n < len(p), nil) without an error must not be allowed to silently
// truncate the output.
func TestRenderRolePropagatesShortWrites(t *testing.T) {
	res := resolver.Result{TotalApplyPerms: []string{"a.b.c"}}

	err := RenderRole(shortWriter{}, res, "role_x", "v", "d")
	if err == nil {
		t.Fatal("RenderRole with a short writer returned nil; expected io.ErrShortWrite to be latched and surfaced")
	}
	if !errors.Is(err, io.ErrShortWrite) {
		t.Errorf("RenderRole error chain does not wrap io.ErrShortWrite.\nerr: %v", err)
	}
}

// stripYAMLComments returns input with all leading-`#` comment lines
// removed. The role-file header is a sequence of YAML comments we
// want to assert independently of the YAML body — yaml.Unmarshal
// silently ignores comments, so this is structurally a no-op for
// round-trip tests, but stripping them up front makes ordering-based
// substring assertions (e.g. "a.b.c appears before m.n.o") immune
// to a header line that happens to contain a permission-shaped string.
func stripYAMLComments(in string) string {
	var b strings.Builder
	for line := range strings.SplitSeq(in, "\n") {
		if strings.HasPrefix(strings.TrimSpace(line), "#") {
			continue
		}
		b.WriteString(line)
		b.WriteByte('\n')
	}
	return b.String()
}
