package reporter

import (
	"fmt"
	"io"

	"gopkg.in/yaml.v3"

	"github.com/thoreinstein/tfperms/internal/resolver"
)

// roleStage is the lifecycle stage advertised in the rendered YAML. GCP
// custom-role files require the field; "GA" is the right default for a
// role users are about to create from a static analysis of their own
// configuration. The stage is intentionally not exposed as a flag — a
// caller who wants ALPHA/BETA can edit one line of the generated file
// and a flag would only multiply the surface without changing the
// permissions, which are the actual subject of this report.
const roleStage = "GA"

// roleDocument is the wire shape of the GCP custom-role YAML file. The
// field set matches the `gcloud iam roles create --file=...` schema: a
// human-readable Title, a lifecycle Stage, and the list of permission
// strings the role grants. Marshalling through a typed struct (rather
// than a yaml.Node tree) keeps the field order stable across yaml.v3
// versions and makes a missing field a compile error rather than a
// silent omission.
//
// The yaml tags pin the wire names because the Go field names are
// idiomatic Go (Title) but gcloud expects camelCase
// (`includedPermissions`). Without explicit tags, yaml.v3 would emit
// `includedpermissions` (all lower) which gcloud rejects.
type roleDocument struct {
	Title               string   `yaml:"title"`
	Stage               string   `yaml:"stage"`
	IncludedPermissions []string `yaml:"includedPermissions"`
}

// RenderRole writes a GCP custom-role YAML file representation of res
// to w. The output is suitable for `gcloud iam roles create
// <ROLE_ID> --project=<PROJECT_ID> --file=role.yaml`.
//
// roleName is used both as the role identifier in the gcloud command
// shown in the header and as the YAML `title` field. Callers must
// validate it against the GCP role-ID regex (^[a-zA-Z0-9_]{3,64}$)
// before calling RenderRole — this function does not re-validate.
//
// version and date are the build-metadata strings recorded in the
// generated file's header comment so a reader can tell which tfperms
// build produced the output. They map to main.version and main.date at
// the CLI layer; tests pass synthetic values.
//
// The IncludedPermissions list is sourced from
// resolver.Result.TotalApplyPerms — the permissions a service account
// running `terraform apply` actually needs (apply has to refresh state
// first, so it inherits the plan permissions). Canonicalize is called
// on entry so output is deterministic regardless of resolver field
// ordering, mirroring Render's contract.
//
// All writes flow through errWriter so a broken stdout pipe surfaces as
// a non-nil return rather than silent truncation under exit code 0.
func RenderRole(w io.Writer, res resolver.Result, roleName, version, date string) error {
	res = Canonicalize(res)
	ew := &errWriter{w: w}

	fmt.Fprintf(ew, "# Generated by tfperms %s on %s\n", version, date)
	fmt.Fprintln(ew, "#")
	fmt.Fprintln(ew, "# Apply this role with:")
	fmt.Fprintf(ew, "#   gcloud iam roles create %s --project=PROJECT_ID --file=role.yaml\n", roleName)

	doc := roleDocument{
		Title:               roleName,
		Stage:               roleStage,
		IncludedPermissions: res.TotalApplyPerms,
	}

	encoder := yaml.NewEncoder(ew)
	encoder.SetIndent(2)
	if err := encoder.Encode(doc); err != nil {
		// Flush any pending writer error first: a broken pipe latched
		// during the header would otherwise be masked by the encoder
		// surfacing its own write error from the same source. Either
		// way, returning a wrapped error preserves the underlying
		// cause for errors.Is comparisons.
		if ew.err != nil {
			return fmt.Errorf("write role yaml: %w", ew.err)
		}
		return fmt.Errorf("encode role yaml: %w", err)
	}
	if err := encoder.Close(); err != nil {
		if ew.err != nil {
			return fmt.Errorf("write role yaml: %w", ew.err)
		}
		return fmt.Errorf("close role yaml encoder: %w", err)
	}

	if ew.err != nil {
		return fmt.Errorf("write role yaml: %w", ew.err)
	}
	return nil
}
